### ISSUE TITLE
ClassCastException in BeanBinder

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#292]
The following exception may be thrown:

```
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast java.lang.Integer to int
    at com.vaadin.data.BeanBinder$BeanBindingImpl.lambda$createConverter$48(BeanBinder.java:239)
    at com.vaadin.data.Result.of(Result.java:90)
    at com.vaadin.data.util.converter.Converter.lambda$from$19(Converter.java:103)
    at com.vaadin.data.util.converter.Converter$1.convertToModel(Converter.java:128)
    at com.vaadin.data.util.converter.Converter$2.lambda$convertToModel$20(Converter.java:163)
    at com.vaadin.data.SimpleResult.flatMap(SimpleResult.java:63)
    at com.vaadin.data.util.converter.Converter$2.convertToModel(Converter.java:163)
    at com.vaadin.data.util.converter.Converter$2.convertToModel(Converter.java:161)
    at com.vaadin.data.Binder$BindingImpl.doValidation(Binder.java:547)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
    at com.vaadin.data.Binder$BindingImpl.handleFieldValueChange(Binder.java:587)
    at com.vaadin.data.Binder$BindingImpl.lambda$bind$eb8ce9e7$1(Binder.java:527)
    at com.vaadin.data.Binder$2.lambda$addValueChangeListener$268e65f9$1(Binder.java:785)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
    ... 74 common frames omitted
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Integer to int
    at java.lang.Class.cast(Class.java:3369)
    at com.vaadin.data.BeanBinder$BeanBindingImpl.lambda$createConverter$46(BeanBinder.java:237)
    at com.vaadin.data.util.converter.Converter.lambda$null$18(Converter.java:103)
    at com.vaadin.data.Result.of(Result.java:88)
```

No need to call `cast` method since it seems it's no able to understand boxing/unboxing.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/14441

**Comment by jdahlstrom** [comment]
The cast is there to force an early error in case of incompatible types. However,  primitive types and their wrappers are a special case that should be handled somehow.
