### ISSUE TITLE
CheckBoxGroup is not Serializable

### ISSUE THREAD

**Issue by johndevs** [vaadin/framework8-issues#409]
When trying to serialize the CheckBoxGroup the following is thrown:

Storing Lamba in a non-transient field?

```
Caused by: java.io.NotSerializableException: com.vaadin.ui.CheckBoxGroup$$Lambda$123/1450587338
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:136)
    ... 48 more
```

**Comment by Legioth** [comment]
The same will be true for all of our new components that use functional interfaces until we update them to use serializable versions of the standard `java.util.function` interfaces.

You might be able to work around this by following this really ugly pattern in your application code:

`checkBoxGroup.setItemEnabledProvider((Predicate<MyType> & Serializable) Original::lambda);`

**Comment by Legioth** [comment]
I just realized that the problem here is actually that there's a default item enabled provider (`item -> true`) that isn't serializable. We should really create a test that loop over all our component classes, creates an instance using the default constructor and tests that the instance can be serialized.

**Comment by pleku** [comment]
Fix all the non-args component constructors that create a not-serializable field.

Needs test for the non-args constructors for all components to be serializable, and a test to verify that none of the fields in any classes are of type java.util.function and not serializable.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14615/

**Comment by johndevs** [comment]
:tada:
