### ISSUE TITLE
Gird: add column "back" (after removal) may lead to an exception.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-issues#590]
Use `GridColspans` UI from here: https://github.com/vaadin/framework/tree/589-grid-tests-migration.
Click "Show/Hide first name" button.
The result: column disappears.
Click one more time to the same button.
Expected: Column should be added back (there is an open question what should happen with merged cells).
The result (might be related or not to the joined columns functionality): 

java.lang.IllegalArgumentException: No cell found for column id 5
	at com.vaadin.ui.components.grid.StaticSection$StaticRow.internalGetCell(StaticSection.java:219)
	at com.vaadin.ui.components.grid.StaticSection$StaticRow.getCell(StaticSection.java:202)
	at com.vaadin.ui.components.grid.Footer$Row.getCell(Footer.java:1)
	at com.vaadin.ui.Grid.lambda$4(Grid.java:2001)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.vaadin.ui.Grid.iterator(Grid.java:2000)
	at com.vaadin.server.AbstractClientConnector.getAllChildrenIterable(AbstractClientConnector.java:536)
	at com.vaadin.ui.ConnectorTracker.isHierarchyComplete(ConnectorTracker.java:451)
	at com.vaadin.ui.ConnectorTracker.cleanConnectorMap(ConnectorTracker.java:286)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:334)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1450)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at com.vaadin.launcher.ApplicationRunnerServlet.service(ApplicationRunnerServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

**Comment by pleku** [comment]
Related to #493 ? Which is the same as vaadin/framework#8057

**Comment by denis-anisimov** [comment]
I would say not at all.

The difference is:
- It's possible to remove a column (in this case).
- It's not possible to add it back.
- There is no client side exception (at least I don't see it). There is a server side exception.
